name: CI

on:
  pull_request:
    paths:
      - "aws/sb/**"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws/sb

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.14"

      - name: Init
        run: terraform init -backend=false

      - name: Format
        run: terraform fmt -recursive -check

      - name: Validate
        run: terraform validate
